/**:
  ros__parameters:
    radial_resolution_m: 0.5
    azimuth_resolution_rad: 0.0175
    elevation_resolution_rad: 0.0175
    voxel_points_threshold: 2
    min_radius_m: 0.5
    max_radius_m: 300.0
    intensity_threshold: 2
    visibility_estimation_max_range_m: 20.0
    visibility_estimation_min_azimuth_rad: 0.0
    visibility_estimation_max_azimuth_rad: 6.28
    visibility_estimation_min_elevation_rad: -1.57
    visibility_estimation_max_elevation_rad: 1.57
    use_return_type_classification: true
    filter_secondary_returns: false
    secondary_noise_threshold: 4
    low_visibility_entropy_threshold: 0.3
    low_visibility_anisotropy_threshold: 0.95
    low_visibility_average_intensity_threshold: 2.0
    low_visibility_sparse_voxel_point_count_threshold: 10
    low_visibility_sparse_voxel_secondary_return_ratio_threshold: 0.2
    visibility_estimation_max_secondary_voxel_count: 500
    primary_return_types: [1, 6, 8, 10]
    visibility_estimation_only: false
    publish_noise_cloud: false
    publish_low_visibility_voxels: false
    publish_area_marker: false
    filter_ratio_error_threshold: 0.5
    filter_ratio_warn_threshold: 0.7
    visibility_error_threshold: 0.8
    visibility_warn_threshold: 0.9
    num_frames_hysteresis_transition: 1
    immediate_report_error: false
    immediate_relax_state: false
