base_branch: feat/v0.64/e2e
branch_out_commit: 30ab4fa171ee606a78fdd90bf051f2fe984c3577
created_at: 2026-08-05T00:32:33Z
product_name: diffusion_planner
experiment_branch: feat/v0.64/e2e-experiment_08_05
pilot_auto_sync_branch: feat/v4.4/e2e-experiment_08_05
