/**:
  ros__parameters:
    plugins_path: $(find-pkg-share autoware_tensorrt_plugins)/plugins/libautoware_tensorrt_plugins.so
    model:
      backend: "tensorrt" # "tensorrt" "ort_cpu" "ort_cuda" "ort_tensorrt"
      precision: "fp32"
      use_cuda_graph: false
      onnx_model_path: $(var data_path)/diffusion_planner/diffusion_planner_sampler.onnx
    planning_frequency_hz: 10.0
    traffic_light_group_msg_timeout_seconds: 0.2
    batch_size: 1
    noise_scale: [1.0]
    line_string_max_step_m: 5.0
    planning_factor:
      enable_stop: true
      enable_slowdown: false
      stop_keep_duration_threshold: 1.0  # [s]
      stop_velocity_threshold: 0.1       # [m/s]
      slowdown_accel_threshold: -0.3     # [m/s^2]
    debug_params:
      publish_debug_route: true
      publish_debug_map: false
      publish_debug_linestrings: true
