/**:
  ros__parameters:
    use_operation_mode_availability: true
    initial_latch_suppression: true
    rate: 10.0
    input_qos_depth: 1000
    graph_qos_depth: 1
    allow_override_for_debugging: false  # DO NOT set to true except for debugging.

    use_command_mode_mappings: true
    command_mode_mappings:
      - "{mode: 1001, path: /autoware/modes/stop}"
      - "{mode: 1002, path: /autoware/modes/autonomous}"
      - "{mode: 1003, path: /autoware/modes/local}"
      - "{mode: 1004, path: /autoware/modes/remote}"
      - "{mode: 2001, path: /autoware/modes/emergency_stop}"
      - "{mode: 2002, path: /autoware/modes/comfortable_stop}"
      - "{mode: 2003, path: /autoware/modes/pull_over}"

    use_driving_mode_mappings: true
    driving_mode_available:
      - "{mode: 1001, path: /autoware/modes/stop}"
      - "{mode: 1002, path: /autoware/modes/autonomous/available}"
      - "{mode: 1003, path: /autoware/modes/local}"
      - "{mode: 1004, path: /autoware/modes/remote}"
      - "{mode: 2001, path: /autoware/modes/emergency_stop}"
      - "{mode: 2002, path: /autoware/modes/comfortable_stop}"
      - "{mode: 2003, path: /autoware/modes/pull_over}"
    driving_mode_continuable:
      - "{mode: 1001, path: /autoware/modes/stop}"
      - "{mode: 1002, path: /autoware/modes/autonomous}"
      - "{mode: 1003, path: /autoware/modes/local}"
      - "{mode: 1004, path: /autoware/modes/remote}"
      - "{mode: 2001, path: /autoware/modes/emergency_stop}"
      - "{mode: 2002, path: /autoware/modes/comfortable_stop}"
      - "{mode: 2003, path: /autoware/modes/pull_over}"
