/**:
  ros__parameters:
    # generate_parameter_library parameters
    planning_frequency_hz: 10.0
    plugin_names:
      - "autoware::minimum_rule_based_planner::plugin::ObstacleStop"
      - "autoware::minimum_rule_based_planner::plugin::SurroundObstacleStop"
      - "autoware::minimum_rule_based_planner::plugin::ObstacleSlowDown"

    path_planning:
      path_length:
        backward: 5.0
        forward: 300.0

      early_stop:
        enable: false
        expected_ego_speed_parking: 2.8
        max_lat_accel_parking: 0.8
        max_decel_parking: 1.0
        max_jerk_parking: 1.0

      # Used only when early_stop.enable is false
      start_goal_planner:
        reference_velocity: 2.78
        steer_angle_trial_count: 20
        max_steer_angle_rate: 30.0
        eval_weight_curvature: 0.1
        eval_weight_length: 0.4
        eval_weight_diff: 0.5
        traj_generation_exit_count: 7
        goal_planner:
          activate_distance_traj: 40.0
          activate_distance_ego: 80.0
          pre_goal_offset: 3.0
          num_start_poses: 80
        start_planner:
          max_path_range: 30.0
          num_goal_poses: 15

      lane_change_failure_stop_margin: 0.0

      ego_nearest_lanelet:
        dist_threshold: 10.0
        yaw_threshold: 1.57

      path_shift:
        enable: true
        start_time_offset: 0.1
        minimum_shift_length: 0.5
        minimum_shift_distance: 3.0
        min_speed_for_curvature: 1.39  # [m/s] 5 km/h
        lateral_accel_limit: 0.8      # [m/s^2]
        curvature_limit: 0.156          # [1/m] R = 10 m

      waypoint_group:
        separation_threshold: 1.0
        interval_margin_ratio: 10.0

      output:
        delta_arc_length: 0.5

    map_based_stop:
      stop_margin_distance: 0.0 # [m]
      stop_distance_from_crosswalk: 3.5 # [m]
      stop_distance_from_private_area: 3.0 # [m]
      stop_distance_from_intersection: 1.0 # [m]
      stop_distance_from_road_shoulder: 0.5 # [m]
      max_deceleration: 4.0 # [m/s^2]
      max_jerk: 5.0 # [m/s^3]
      stop_point_diff_threshold: 0.5 # [m]

    turn_signal:
      search_distance: 30.0 # [m]
      min_blink_duration: 3.0 # [s]
      stopped_velocity_threshold: 0.1 # [m/s]
      heading_align_threshold: 0.15 # [rad]

    obstacle_stop:
      enable: true
      use_objects: true
      use_pointcloud: true
      enable_stop_for_objects: true
      enable_stop_for_pointcloud: false
      stop_margin: 6.0
      nominal_stopping_decel: 1.0 # [m/s^2]
      maximum_stopping_decel: 4.0 # [m/s^2]
      stopping_jerk: 3.0 # [m/s^3]
      delay_response_time: 0.5 #[s]
      on_time_buffer: 0.5 # [s]
      off_time_buffer: 0.7 # [s]
      arrived_distance_threshold: 0.5 # threshold to check if the ego vehicle has arrived at the stop point [m]

      objects:
        target_objects:
          bbox: ["car", "truck", "bus", "trailer", "motorcycle", "bicycle", "pedestrian", "hazard", "unknown"]
          polygon: ["car", "truck", "bus", "trailer", "pedestrian", "hazard", "unknown"]
          pointcloud: ["structure", "vegetation"]
        stopped_velocity_th: 0.3 # velocity threshold for target object to be considered as stopped [m/s]
        max_lateral_velocity_th: 1.0 # maximum lateral velocity threshold for target object [m/s]
        safety_buffer: 0.1       # safety buffer to expand object shape [m]
        pointcloud_height_buffer: 0.5
        pointcloud_min_height: 0.2
        lateral_margin:
          car: 0.2
          truck: 0.2
          bus: 0.2
          trailer: 0.2
          motorcycle: 0.2
          bicycle: 0.2
          pedestrian: 0.2
          hazard: 0.2
          structure: 0.2
          vegetation: 0.2
          unknown: 0.2

      rss_params:
        enable: true
        object_decel:
          car: 1.6
          truck: 1.6
          bus: 1.6
          trailer: 1.6
          motorcycle: 2.0
          bicycle: 3.0
          pedestrian: 5.0
        ego_decel: 2.0           # [m/s^2]
        safety_margin: 1.5       # [m]
        lookahead_horizon: 1.5   # [s]

    surround_obstacle_stop:
      enable: true
      use_objects: true
      use_pointcloud: false
      target_objects:
        bbox: ["car", "truck", "bus", "trailer", "motorcycle", "bicycle", "pedestrian", "hazard", "animal", "unknown"]
        polygon: ["car", "truck", "bus", "trailer", "pedestrian", "hazard", "animal", "unknown"]
        pointcloud: ["structure", "vegetation"]
      front_distance_th:
        car: 0.5
        truck: 0.5
        bus: 0.5
        trailer: 0.5
        motorcycle: 0.5
        bicycle: 0.5
        pedestrian: 0.5
        hazard: 0.5
        animal: 0.5
        unknown: 0.5
        pointcloud: 0.5
      side_distance_th:
        car: 0.0
        truck: 0.0
        bus: 0.0
        trailer: 0.0
        motorcycle: 1.0
        bicycle: 1.0
        pedestrian: 1.0
        hazard: 0.5
        animal: 0.5
        unknown: 0.5
        pointcloud: 0.5
      back_distance_th:
        car: 0.0
        truck: 0.0
        bus: 0.0
        trailer: 0.0
        motorcycle: 0.5
        bicycle: 0.5
        pedestrian: 0.5
        hazard: 0.5
        animal: 0.5
        unknown: 0.5
        pointcloud: 0.5
      hysteresis_distance: 0.1 # [m]
      hysteresis_time: 0.2     # [s]
      ego_stopped_vel_th: 0.1  # [m/s]
      pcd_height_buffer: 0.5  # height buffer to add above ego height [m]
      pcd_min_height: 0.2  # minimum height of pointcloud [m]

    obstacle_slow_down:
      enable: true
      slow_down_min_acc: -1.0         # slow down min deceleration [m/ss]
      slow_down_min_jerk: -1.0        # slow down min jerk [m/sss]
      lpf_gain_slow_down_vel: 0.9     # low-pass filter gain for slow down velocity
      lpf_gain_lateral_distance: 0.7  # low-pass filter gain for lateral distance from obstacle to ego's path
      lpf_gain_dist_to_slow_down: 0.7 # low-pass filter gain for distance to slow down start
      time_margin_on_target_velocity: 1.5 # [s]
      target_objects: ["car", "truck", "bus", "trailer", "motorcycle", "bicycle", "pedestrian", "hazard", "animal"]
      obstacle_filtering:
        min_lat_margin: -10.0  # lateral margin between obstacle and trajectory band with ego's width to avoid the conflict with the obstacle_stop [m]
        max_lat_margin: 1.1    # lateral margin between obstacle and trajectory band with ego's width [m]
        lat_hysteresis_margin: 0.2
        max_lat_velocity: 3.0  # [m/s] max lateral velocity of obstacle to be considered
        time_to_entry_slow_down_condition: 0.5
        time_to_exit_slow_down_condition: 0.5
      trajectory_polygon:
        decimate_trajectory_step_length: 2.0 # [m]
        goal_extended_trajectory_length: 6.0 # [m]
        enable_to_consider_current_pose: true
        time_to_convergence: 1.5 # [s]
      moving_object_speed_threshold: 0.5 # [m/s] how fast the object needs to move to be considered as "moving"
      moving_object_hysteresis_range: 0.1 # [m/s] hysteresis range used to prevent chattering when obstacle moves close to moving_object_speed_threshold
      object_type_specified_params:
        default:  # values used if not specified for some object type
          left:
            moving:
              min_lat_margin: 0.2
              max_lat_margin: 1.5
              min_ego_velocity: 2.0
              max_ego_velocity: 12.0
            static:
              min_lat_margin: 0.2
              max_lat_margin: 1.8
              min_ego_velocity: 4.0
              max_ego_velocity: 12.0
          right:
            moving:
              min_lat_margin: 0.2
              max_lat_margin: 1.5
              min_ego_velocity: 2.0
              max_ego_velocity: 12.0
            static:
              min_lat_margin: 0.2
              max_lat_margin: 1.8
              min_ego_velocity: 4.0
              max_ego_velocity: 12.0
          wheel_off_track_scale: 0.0 # scale factor for additional stop margin against ego's wheel off-track. Even if this value is set to 0.0, the planner considers the nominal wheel off-track.
        pedestrian:
          right:
            moving:
              min_lat_margin: 0.5
              max_lat_margin: 2.8
              min_ego_velocity: 0.925
              max_ego_velocity: 9.72
            static:
              min_lat_margin: 0.3
              max_lat_margin: 2.5
              min_ego_velocity: 0.925
              max_ego_velocity: 9.72
          left:
            moving:
              min_lat_margin: 0.5
              max_lat_margin: 2.8
              min_ego_velocity: 0.925
              max_ego_velocity: 9.72
            static:
              min_lat_margin: 0.3
              max_lat_margin: 2.5
              min_ego_velocity: 0.925
              max_ego_velocity: 9.72
          wheel_off_track_scale: 0.6
        bicycle:
          right:
            moving:
              min_lat_margin: 0.5
              max_lat_margin: 2.8
              min_ego_velocity: 0.925
              max_ego_velocity: 9.72
            static:
              min_lat_margin: 0.3
              max_lat_margin: 2.5
              min_ego_velocity: 0.925
              max_ego_velocity: 9.72
          left:
            moving:
              min_lat_margin: 0.5
              max_lat_margin: 2.8
              min_ego_velocity: 0.925
              max_ego_velocity: 9.72
            static:
              min_lat_margin: 0.3
              max_lat_margin: 2.5
              min_ego_velocity: 0.925
              max_ego_velocity: 9.72
          wheel_off_track_scale: 0.6
        motorcycle:
          wheel_off_track_scale: 0.6

    velocity_smoother:
      nearest_dist_threshold_m: 1.5
      nearest_yaw_threshold_deg: 60.0
      target_pull_out_speed_mps: 0.25
      target_pull_out_acc_mps2: 0.5
      max_speed_mps: 13.88
      max_lateral_accel_mps2: 1.5
      set_engage_speed: true
      limit_speed: true
      limit_lateral_acceleration: false
      smooth_velocities: true
      stop_dist_to_prohibit_engage: 0.5

    post_resample:
      max_trajectory_length: 300.0
      min_trajectory_length: 30.0
      resample_time: 10.0
      dense_resample_dt: 0.1
      dense_min_interval_distance: 0.1
      sparse_resample_dt: 0.1
      sparse_min_interval_distance: 1.0

    debug:
      enable_path: true
      enable_shifted_trajectory: true
      enable_optimizer_trajectory: true
      enable_modifier_trajectory: true
      enable_output_trajectory: true
