/**:
  ros__parameters:
    update_interval: 0.3
    max_pose_lag: 0.5 # [s] max interval between consecutive poses for pose velocity
    max_stamp_lag: 0.2 # [s] max timestamp difference between pose and IMU/velocity report
    sensor_buffer_duration: 1.0 # [s] rolling buffer length for IMU and velocity report
    initial_speed_scale_factor: 1.0
    initial_speed_scale_factor_covariance: 0.05
    process_noise_covariance: 1.0e-6
    measurement_noise_covariance: 20.0
    max_angular_velocity: 0.0105 # [rad/s] 0.6 [deg/s]
    max_speed: 17.0 # [m/s]
    min_speed: 6.0 # [m/s]
