<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>autoware_redundancy_adapi_switcher</name>
  <version>0.53.0</version>
  <description>Selects and forwards adapi outputs (MrmState, DiagGraph) from the active ECU in a redundant Autoware system</description>

  <maintainer email="tetsuhiro.kawaguchi@tier4.jp">Tetsuhiro Kawaguchi</maintainer>
  <maintainer email="makoto.kurihara@tier4.jp">Makoto Kurihara</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>
  <buildtool_depend>autoware_cmake</buildtool_depend>

  <depend>autoware_adapi_v1_msgs</depend>
  <depend>autoware_agnocast_wrapper</depend>
  <depend>autoware_default_adapi_universe</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>tier4_external_api_msgs</depend>
  <depend>tier4_system_msgs</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>autoware_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
