<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>autoware_redundancy_switcher_interface_plugins</name>
  <version>0.53.0</version>
  <description>IAdapterPlugin implementations for autoware_redundancy_switcher_interface. Includes RedundancySwitcherAdapter (for https://github.com/tier4/redundancy_switcher via UDS protocol) and NonRedundantSwitcherAdapter (for single-ECU non-redundant systems).</description>
  <maintainer email="tetsuhiro.kawaguchi@tier4.jp">Tetsuhiro Kawaguchi</maintainer>
  <maintainer email="mokoto.kurihara@tier4.jp">Mokoto Kurihara</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>
  <buildtool_depend>autoware_cmake</buildtool_depend>

  <depend>autoware_redundancy_switcher_interface</depend>
  <depend>diagnostic_msgs</depend>
  <depend>diagnostic_updater</depend>
  <depend>nlohmann-json-dev</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>tier4_system_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
