/**:
  ros__parameters:
    vehicle_kinematics:
      max:
        lon_accel_min_mps2: -1.0 # [m/s^2] deceleration
        lon_accel_max_mps2: 1.0 # [m/s^2] acceleration
        lon_jerk_mps3: 5.0 # [m/s^3]
        lat_accel_mps2: 1.5 # [m/s^2] about the limit of grip
        steer_rate_radps: 0.256 # [rad/s]
      nominal:
        lon_accel_min_mps2: -1.0 # [m/s^2] deceleration
        lon_accel_max_mps2: 1.0 # [m/s^2] acceleration
        lon_jerk_mps3: 1.0 # [m/s^3]
        lat_accel_mps2: 1.0 # [m/s^2]
